include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/video_downloader_flutter/**"

linter:
  rules:
    library_private_types_in_public_api: false