name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.8.0-nullsafety.1
homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  xml: ^5.0.2
  equatable: ^2.0.0
  meta: ^1.3.0
  json_annotation: ^4.0.0
  collection: ^1.15.0

dev_dependencies:
  effective_dart: ^1.3.0
  console: ^3.1.0
  test: ^1.16.5
  grinder: ^0.9.0-nullsafety.0
  pedantic: ^1.11.0
  json_serializable: ^4.0.2
  build_runner: ^1.11.5
