name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.10.8

homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^0.15.0
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.3.0
  meta: ^1.3.0
  xml: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.4
  console: ^4.1.0
  freezed: ^0.15.1+1
  grinder: ^0.9.0
  json_serializable: ^6.0.1
  lint: ^1.7.2
  test: ^1.18.2
